DROP TYPE IF EXISTS T_ORDER_STATUS;
CREATE TYPE T_ORDER_STATUS AS ENUM ('NEW', 'PROCESSING', 'INVALID', 'PROCESSED');

CREATE TABLE IF NOT EXISTS orders
(
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users ON DELETE CASCADE,
    number VARCHAR(255) NOT NULL CONSTRAINT orders_number_unique UNIQUE,
    status T_ORDER_STATUS NOT NULL,
    accrual NUMERIC(10, 2) NOT NULL DEFAULT 0,
    uploaded_at TIMESTAMP(0) NOT NULL
);
