// Code generated by MockGen. DO NOT EDIT.
// Source: register.go
//
// Generated by this command:
//
//	mockgen -source=register.go -destination=mocks/mock_registerservice.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockregisterService is a mock of registerService interface.
type MockregisterService struct {
	ctrl     *gomock.Controller
	recorder *MockregisterServiceMockRecorder
	isgomock struct{}
}

// MockregisterServiceMockRecorder is the mock recorder for MockregisterService.
type MockregisterServiceMockRecorder struct {
	mock *MockregisterService
}

// NewMockregisterService creates a new mock instance.
func NewMockregisterService(ctrl *gomock.Controller) *MockregisterService {
	mock := &MockregisterService{ctrl: ctrl}
	mock.recorder = &MockregisterServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockregisterService) EXPECT() *MockregisterServiceMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockregisterService) Register(ctx context.Context, login, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, login, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockregisterServiceMockRecorder) Register(ctx, login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockregisterService)(nil).Register), ctx, login, password)
}
