// Code generated by MockGen. DO NOT EDIT.
// Source: login.go
//
// Generated by this command:
//
//	mockgen -source=login.go -destination=mocks/mock_loginservice.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockloginService is a mock of loginService interface.
type MockloginService struct {
	ctrl     *gomock.Controller
	recorder *MockloginServiceMockRecorder
	isgomock struct{}
}

// MockloginServiceMockRecorder is the mock recorder for MockloginService.
type MockloginServiceMockRecorder struct {
	mock *MockloginService
}

// NewMockloginService creates a new mock instance.
func NewMockloginService(ctrl *gomock.Controller) *MockloginService {
	mock := &MockloginService{ctrl: ctrl}
	mock.recorder = &MockloginServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockloginService) EXPECT() *MockloginServiceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockloginService) Login(ctx context.Context, login, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, login, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockloginServiceMockRecorder) Login(ctx, login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockloginService)(nil).Login), ctx, login, password)
}
