// Code generated by MockGen. DO NOT EDIT.
// Source: orderlister.go
//
// Generated by this command:
//
//	mockgen -source=orderlister.go -destination=mocks/mock_orderliststore.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	query "github.com/korobkovandrey/gmartloyalty/db/query"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderListStore is a mock of OrderListStore interface.
type MockOrderListStore struct {
	ctrl     *gomock.Controller
	recorder *MockOrderListStoreMockRecorder
	isgomock struct{}
}

// MockOrderListStoreMockRecorder is the mock recorder for MockOrderListStore.
type MockOrderListStoreMockRecorder struct {
	mock *MockOrderListStore
}

// NewMockOrderListStore creates a new mock instance.
func NewMockOrderListStore(ctrl *gomock.Controller) *MockOrderListStore {
	mock := &MockOrderListStore{ctrl: ctrl}
	mock.recorder = &MockOrderListStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderListStore) EXPECT() *MockOrderListStoreMockRecorder {
	return m.recorder
}

// GetOrdersForUserID mocks base method.
func (m *MockOrderListStore) GetOrdersForUserID(ctx context.Context, userID int64) ([]query.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersForUserID", ctx, userID)
	ret0, _ := ret[0].([]query.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersForUserID indicates an expected call of GetOrdersForUserID.
func (mr *MockOrderListStoreMockRecorder) GetOrdersForUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersForUserID", reflect.TypeOf((*MockOrderListStore)(nil).GetOrdersForUserID), ctx, userID)
}
