// Code generated by MockGen. DO NOT EDIT.
// Source: withdrawals.go
//
// Generated by this command:
//
//	mockgen -source=withdrawals.go -destination=mocks/mock_withdrawalsstore.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	query "github.com/korobkovandrey/gmartloyalty/db/query"
	gomock "go.uber.org/mock/gomock"
)

// MockWithdrawalsStore is a mock of WithdrawalsStore interface.
type MockWithdrawalsStore struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawalsStoreMockRecorder
	isgomock struct{}
}

// MockWithdrawalsStoreMockRecorder is the mock recorder for MockWithdrawalsStore.
type MockWithdrawalsStoreMockRecorder struct {
	mock *MockWithdrawalsStore
}

// NewMockWithdrawalsStore creates a new mock instance.
func NewMockWithdrawalsStore(ctrl *gomock.Controller) *MockWithdrawalsStore {
	mock := &MockWithdrawalsStore{ctrl: ctrl}
	mock.recorder = &MockWithdrawalsStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawalsStore) EXPECT() *MockWithdrawalsStoreMockRecorder {
	return m.recorder
}

// GetWithdrawalsForUserID mocks base method.
func (m *MockWithdrawalsStore) GetWithdrawalsForUserID(ctx context.Context, userID int64) ([]query.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawalsForUserID", ctx, userID)
	ret0, _ := ret[0].([]query.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawalsForUserID indicates an expected call of GetWithdrawalsForUserID.
func (mr *MockWithdrawalsStoreMockRecorder) GetWithdrawalsForUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawalsForUserID", reflect.TypeOf((*MockWithdrawalsStore)(nil).GetWithdrawalsForUserID), ctx, userID)
}
