// Code generated by MockGen. DO NOT EDIT.
// Source: withdraw.go
//
// Generated by this command:
//
//	mockgen -source=withdraw.go -destination=mocks/mock_withdrawstore.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	query "github.com/korobkovandrey/gmartloyalty/db/query"
	gomock "go.uber.org/mock/gomock"
)

// MockWithdrawStore is a mock of WithdrawStore interface.
type MockWithdrawStore struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawStoreMockRecorder
	isgomock struct{}
}

// MockWithdrawStoreMockRecorder is the mock recorder for MockWithdrawStore.
type MockWithdrawStoreMockRecorder struct {
	mock *MockWithdrawStore
}

// NewMockWithdrawStore creates a new mock instance.
func NewMockWithdrawStore(ctrl *gomock.Controller) *MockWithdrawStore {
	mock := &MockWithdrawStore{ctrl: ctrl}
	mock.recorder = &MockWithdrawStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawStore) EXPECT() *MockWithdrawStoreMockRecorder {
	return m.recorder
}

// Balance mocks base method.
func (m *MockWithdrawStore) Balance(ctx context.Context, userID int64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Balance", ctx, userID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Balance indicates an expected call of Balance.
func (mr *MockWithdrawStoreMockRecorder) Balance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Balance", reflect.TypeOf((*MockWithdrawStore)(nil).Balance), ctx, userID)
}

// CreateWithdraw mocks base method.
func (m *MockWithdrawStore) CreateWithdraw(ctx context.Context, arg query.CreateWithdrawParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithdraw", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWithdraw indicates an expected call of CreateWithdraw.
func (mr *MockWithdrawStoreMockRecorder) CreateWithdraw(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithdraw", reflect.TypeOf((*MockWithdrawStore)(nil).CreateWithdraw), ctx, arg)
}
