// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go
//
// Generated by this command:
//
//	mockgen -source=auth.go -destination=mocks/mock_userauthstore.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	query "github.com/korobkovandrey/gmartloyalty/db/query"
	gomock "go.uber.org/mock/gomock"
)

// MockUserAuthStore is a mock of UserAuthStore interface.
type MockUserAuthStore struct {
	ctrl     *gomock.Controller
	recorder *MockUserAuthStoreMockRecorder
	isgomock struct{}
}

// MockUserAuthStoreMockRecorder is the mock recorder for MockUserAuthStore.
type MockUserAuthStoreMockRecorder struct {
	mock *MockUserAuthStore
}

// NewMockUserAuthStore creates a new mock instance.
func NewMockUserAuthStore(ctrl *gomock.Controller) *MockUserAuthStore {
	mock := &MockUserAuthStore{ctrl: ctrl}
	mock.recorder = &MockUserAuthStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserAuthStore) EXPECT() *MockUserAuthStoreMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserAuthStore) CreateUser(arg0 context.Context, arg1 query.CreateUserParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserAuthStoreMockRecorder) CreateUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserAuthStore)(nil).CreateUser), arg0, arg1)
}

// GetUserByLogin mocks base method.
func (m *MockUserAuthStore) GetUserByLogin(arg0 context.Context, arg1 string) (query.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", arg0, arg1)
	ret0, _ := ret[0].(query.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockUserAuthStoreMockRecorder) GetUserByLogin(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockUserAuthStore)(nil).GetUserByLogin), arg0, arg1)
}
