// Code generated by MockGen. DO NOT EDIT.
// Source: balance.go
//
// Generated by this command:
//
//	mockgen -source=balance.go -destination=mocks/mock_balancestore.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBalanceStore is a mock of BalanceStore interface.
type MockBalanceStore struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceStoreMockRecorder
	isgomock struct{}
}

// MockBalanceStoreMockRecorder is the mock recorder for MockBalanceStore.
type MockBalanceStoreMockRecorder struct {
	mock *MockBalanceStore
}

// NewMockBalanceStore creates a new mock instance.
func NewMockBalanceStore(ctrl *gomock.Controller) *MockBalanceStore {
	mock := &MockBalanceStore{ctrl: ctrl}
	mock.recorder = &MockBalanceStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceStore) EXPECT() *MockBalanceStoreMockRecorder {
	return m.recorder
}

// Accrual mocks base method.
func (m *MockBalanceStore) Accrual(ctx context.Context, userID int64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accrual", ctx, userID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Accrual indicates an expected call of Accrual.
func (mr *MockBalanceStoreMockRecorder) Accrual(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accrual", reflect.TypeOf((*MockBalanceStore)(nil).Accrual), ctx, userID)
}

// Withdrawn mocks base method.
func (m *MockBalanceStore) Withdrawn(ctx context.Context, userID int64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdrawn", ctx, userID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Withdrawn indicates an expected call of Withdrawn.
func (mr *MockBalanceStoreMockRecorder) Withdrawn(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdrawn", reflect.TypeOf((*MockBalanceStore)(nil).Withdrawn), ctx, userID)
}
