// Code generated by MockGen. DO NOT EDIT.
// Source: ordercreator.go
//
// Generated by this command:
//
//	mockgen -source=ordercreator.go -destination=mocks/mock_ordercreatestore.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	query "github.com/korobkovandrey/gmartloyalty/db/query"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderCreateStore is a mock of OrderCreateStore interface.
type MockOrderCreateStore struct {
	ctrl     *gomock.Controller
	recorder *MockOrderCreateStoreMockRecorder
	isgomock struct{}
}

// MockOrderCreateStoreMockRecorder is the mock recorder for MockOrderCreateStore.
type MockOrderCreateStoreMockRecorder struct {
	mock *MockOrderCreateStore
}

// NewMockOrderCreateStore creates a new mock instance.
func NewMockOrderCreateStore(ctrl *gomock.Controller) *MockOrderCreateStore {
	mock := &MockOrderCreateStore{ctrl: ctrl}
	mock.recorder = &MockOrderCreateStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderCreateStore) EXPECT() *MockOrderCreateStoreMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockOrderCreateStore) CreateOrder(ctx context.Context, arg query.CreateOrderParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderCreateStoreMockRecorder) CreateOrder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderCreateStore)(nil).CreateOrder), ctx, arg)
}

// GetOrderByNumber mocks base method.
func (m *MockOrderCreateStore) GetOrderByNumber(ctx context.Context, number string) (query.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByNumber", ctx, number)
	ret0, _ := ret[0].(query.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByNumber indicates an expected call of GetOrderByNumber.
func (mr *MockOrderCreateStoreMockRecorder) GetOrderByNumber(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByNumber", reflect.TypeOf((*MockOrderCreateStore)(nil).GetOrderByNumber), ctx, number)
}
