// Code generated by MockGen. DO NOT EDIT.
// Source: user.go
//
// Generated by this command:
//
//	mockgen -source=user.go -destination=mocks/mock_userfinderstore.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	query "github.com/korobkovandrey/gmartloyalty/db/query"
	gomock "go.uber.org/mock/gomock"
)

// MockUserFinderStore is a mock of UserFinderStore interface.
type MockUserFinderStore struct {
	ctrl     *gomock.Controller
	recorder *MockUserFinderStoreMockRecorder
	isgomock struct{}
}

// MockUserFinderStoreMockRecorder is the mock recorder for MockUserFinderStore.
type MockUserFinderStoreMockRecorder struct {
	mock *MockUserFinderStore
}

// NewMockUserFinderStore creates a new mock instance.
func NewMockUserFinderStore(ctrl *gomock.Controller) *MockUserFinderStore {
	mock := &MockUserFinderStore{ctrl: ctrl}
	mock.recorder = &MockUserFinderStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserFinderStore) EXPECT() *MockUserFinderStoreMockRecorder {
	return m.recorder
}

// GetUserById mocks base method.
func (m *MockUserFinderStore) GetUserById(arg0 context.Context, arg1 int64) (query.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserById", arg0, arg1)
	ret0, _ := ret[0].(query.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserById indicates an expected call of GetUserById.
func (mr *MockUserFinderStoreMockRecorder) GetUserById(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*MockUserFinderStore)(nil).GetUserById), arg0, arg1)
}
