// Code generated by MockGen. DO NOT EDIT.
// Source: accrual.go
//
// Generated by this command:
//
//	mockgen -source=accrual.go -destination=mocks/mock_orderstore.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	query "github.com/korobkovandrey/gmartloyalty/db/query"
	gomock "go.uber.org/mock/gomock"
)

// MockorderStore is a mock of orderStore interface.
type MockorderStore struct {
	ctrl     *gomock.Controller
	recorder *MockorderStoreMockRecorder
	isgomock struct{}
}

// MockorderStoreMockRecorder is the mock recorder for MockorderStore.
type MockorderStoreMockRecorder struct {
	mock *MockorderStore
}

// NewMockorderStore creates a new mock instance.
func NewMockorderStore(ctrl *gomock.Controller) *MockorderStore {
	mock := &MockorderStore{ctrl: ctrl}
	mock.recorder = &MockorderStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockorderStore) EXPECT() *MockorderStoreMockRecorder {
	return m.recorder
}

// GetOrderByNumber mocks base method.
func (m *MockorderStore) GetOrderByNumber(ctx context.Context, number string) (query.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByNumber", ctx, number)
	ret0, _ := ret[0].(query.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByNumber indicates an expected call of GetOrderByNumber.
func (mr *MockorderStoreMockRecorder) GetOrderByNumber(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByNumber", reflect.TypeOf((*MockorderStore)(nil).GetOrderByNumber), ctx, number)
}

// SetOrderStatus mocks base method.
func (m *MockorderStore) SetOrderStatus(ctx context.Context, arg query.SetOrderStatusParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOrderStatus", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOrderStatus indicates an expected call of SetOrderStatus.
func (mr *MockorderStoreMockRecorder) SetOrderStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOrderStatus", reflect.TypeOf((*MockorderStore)(nil).SetOrderStatus), ctx, arg)
}

// SetOrderStatusAndAccrual mocks base method.
func (m *MockorderStore) SetOrderStatusAndAccrual(ctx context.Context, arg query.SetOrderStatusAndAccrualParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOrderStatusAndAccrual", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOrderStatusAndAccrual indicates an expected call of SetOrderStatusAndAccrual.
func (mr *MockorderStoreMockRecorder) SetOrderStatusAndAccrual(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOrderStatusAndAccrual", reflect.TypeOf((*MockorderStore)(nil).SetOrderStatusAndAccrual), ctx, arg)
}
