// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: balance.sql

package query

import (
	"context"
)

const accrual = `-- name: Accrual :one
SELECT COALESCE(SUM(accrual), 0)::numeric FROM orders WHERE status = 'PROCESSED' AND user_id = $1
`

func (q *Queries) Accrual(ctx context.Context, userID int64) (float64, error) {
	row := q.db.QueryRowContext(ctx, accrual, userID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const withdrawn = `-- name: Withdrawn :one
SELECT COALESCE(SUM(sum), 0)::numeric FROM withdrawals WHERE user_id = $1
`

func (q *Queries) Withdrawn(ctx context.Context, userID int64) (float64, error) {
	row := q.db.QueryRowContext(ctx, withdrawn, userID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}
