// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package query

import (
	"time"
)

type User struct {
	ID        int64
	Login     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
