// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: orders.sql

package query

import (
	"context"
	"time"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, number, status, uploaded_at)
VALUES ($1, $2,  'NEW', $3)
RETURNING id
`

type CreateOrderParams struct {
	UserID     int64
	Number     string
	UploadedAt time.Time
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.UserID, arg.Number, arg.UploadedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getOrderByNumber = `-- name: GetOrderByNumber :one
SELECT id, user_id, number, status, accrual, uploaded_at FROM orders WHERE number=$1 LIMIT 1
`

func (q *Queries) GetOrderByNumber(ctx context.Context, number string) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByNumber, number)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Number,
		&i.Status,
		&i.Accrual,
		&i.UploadedAt,
	)
	return i, err
}

const getOrdersForUserID = `-- name: GetOrdersForUserID :many
SELECT id, user_id, number, status, accrual, uploaded_at FROM orders WHERE user_id=$1 ORDER BY uploaded_at DESC
`

func (q *Queries) GetOrdersForUserID(ctx context.Context, userID int64) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getOrdersForUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Number,
			&i.Status,
			&i.Accrual,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
