// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: withdrawals.sql

package query

import (
	"context"
	"time"
)

const createWithdraw = `-- name: CreateWithdraw :one
INSERT INTO withdrawals (user_id, "order", sum, processed_at)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateWithdrawParams struct {
	UserID      int64
	Order       string
	Sum         float64
	ProcessedAt time.Time
}

func (q *Queries) CreateWithdraw(ctx context.Context, arg CreateWithdrawParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createWithdraw,
		arg.UserID,
		arg.Order,
		arg.Sum,
		arg.ProcessedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getWithdrawalsForUserID = `-- name: GetWithdrawalsForUserID :many
SELECT id, user_id, "order", sum, processed_at FROM withdrawals WHERE user_id=$1 ORDER BY processed_at DESC
`

func (q *Queries) GetWithdrawalsForUserID(ctx context.Context, userID int64) ([]Withdrawal, error) {
	rows, err := q.db.QueryContext(ctx, getWithdrawalsForUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Withdrawal
	for rows.Next() {
		var i Withdrawal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Order,
			&i.Sum,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
