// Code generated by MockGen. DO NOT EDIT.
// Source: list.go
//
// Generated by this command:
//
//	mockgen -source=list.go -destination=mocks/mock_orderlister.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/korobkovandrey/gmartloyalty/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockorderLister is a mock of orderLister interface.
type MockorderLister struct {
	ctrl     *gomock.Controller
	recorder *MockorderListerMockRecorder
	isgomock struct{}
}

// MockorderListerMockRecorder is the mock recorder for MockorderLister.
type MockorderListerMockRecorder struct {
	mock *MockorderLister
}

// NewMockorderLister creates a new mock instance.
func NewMockorderLister(ctrl *gomock.Controller) *MockorderLister {
	mock := &MockorderLister{ctrl: ctrl}
	mock.recorder = &MockorderListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockorderLister) EXPECT() *MockorderListerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockorderLister) List(ctx context.Context, userID int64) ([]service.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].([]service.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockorderListerMockRecorder) List(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockorderLister)(nil).List), ctx, userID)
}
