// Code generated by MockGen. DO NOT EDIT.
// Source: create.go
//
// Generated by this command:
//
//	mockgen -source=create.go -destination=mocks/mock_ordercreator.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockorderCreator is a mock of orderCreator interface.
type MockorderCreator struct {
	ctrl     *gomock.Controller
	recorder *MockorderCreatorMockRecorder
	isgomock struct{}
}

// MockorderCreatorMockRecorder is the mock recorder for MockorderCreator.
type MockorderCreatorMockRecorder struct {
	mock *MockorderCreator
}

// NewMockorderCreator creates a new mock instance.
func NewMockorderCreator(ctrl *gomock.Controller) *MockorderCreator {
	mock := &MockorderCreator{ctrl: ctrl}
	mock.recorder = &MockorderCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockorderCreator) EXPECT() *MockorderCreatorMockRecorder {
	return m.recorder
}

// Push mocks base method.
func (m *MockorderCreator) Push(ctx context.Context, userID int64, orderNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", ctx, userID, orderNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// Push indicates an expected call of Push.
func (mr *MockorderCreatorMockRecorder) Push(ctx, userID, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockorderCreator)(nil).Push), ctx, userID, orderNumber)
}

// MockAccrualPusher is a mock of AccrualPusher interface.
type MockAccrualPusher struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualPusherMockRecorder
	isgomock struct{}
}

// MockAccrualPusherMockRecorder is the mock recorder for MockAccrualPusher.
type MockAccrualPusherMockRecorder struct {
	mock *MockAccrualPusher
}

// NewMockAccrualPusher creates a new mock instance.
func NewMockAccrualPusher(ctrl *gomock.Controller) *MockAccrualPusher {
	mock := &MockAccrualPusher{ctrl: ctrl}
	mock.recorder = &MockAccrualPusherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualPusher) EXPECT() *MockAccrualPusherMockRecorder {
	return m.recorder
}

// PushOrder mocks base method.
func (m *MockAccrualPusher) PushOrder(orderNum string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PushOrder", orderNum)
}

// PushOrder indicates an expected call of PushOrder.
func (mr *MockAccrualPusherMockRecorder) PushOrder(orderNum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushOrder", reflect.TypeOf((*MockAccrualPusher)(nil).PushOrder), orderNum)
}
