// Code generated by MockGen. DO NOT EDIT.
// Source: withdraw.go
//
// Generated by this command:
//
//	mockgen -source=withdraw.go -destination=mocks/mock_withdraw.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockwithdraw is a mock of withdraw interface.
type Mockwithdraw struct {
	ctrl     *gomock.Controller
	recorder *MockwithdrawMockRecorder
	isgomock struct{}
}

// MockwithdrawMockRecorder is the mock recorder for Mockwithdraw.
type MockwithdrawMockRecorder struct {
	mock *Mockwithdraw
}

// NewMockwithdraw creates a new mock instance.
func NewMockwithdraw(ctrl *gomock.Controller) *Mockwithdraw {
	mock := &Mockwithdraw{ctrl: ctrl}
	mock.recorder = &MockwithdrawMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockwithdraw) EXPECT() *MockwithdrawMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *Mockwithdraw) Create(ctx context.Context, userID int64, order string, sum float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, order, sum)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockwithdrawMockRecorder) Create(ctx, userID, order, sum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*Mockwithdraw)(nil).Create), ctx, userID, order, sum)
}
