// Code generated by MockGen. DO NOT EDIT.
// Source: balance.go
//
// Generated by this command:
//
//	mockgen -source=balance.go -destination=mocks/mock_balance.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/korobkovandrey/gmartloyalty/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// Mockbalance is a mock of balance interface.
type Mockbalance struct {
	ctrl     *gomock.Controller
	recorder *MockbalanceMockRecorder
	isgomock struct{}
}

// MockbalanceMockRecorder is the mock recorder for Mockbalance.
type MockbalanceMockRecorder struct {
	mock *Mockbalance
}

// NewMockbalance creates a new mock instance.
func NewMockbalance(ctrl *gomock.Controller) *Mockbalance {
	mock := &Mockbalance{ctrl: ctrl}
	mock.recorder = &MockbalanceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockbalance) EXPECT() *MockbalanceMockRecorder {
	return m.recorder
}

// Balance mocks base method.
func (m *Mockbalance) Balance(ctx context.Context, userID int64) (*service.BalanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Balance", ctx, userID)
	ret0, _ := ret[0].(*service.BalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Balance indicates an expected call of Balance.
func (mr *MockbalanceMockRecorder) Balance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Balance", reflect.TypeOf((*Mockbalance)(nil).Balance), ctx, userID)
}
