// Code generated by MockGen. DO NOT EDIT.
// Source: withdrawals.go
//
// Generated by this command:
//
//	mockgen -source=withdrawals.go -destination=mocks/mock_withdrawals.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/korobkovandrey/gmartloyalty/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// Mockwithdrawals is a mock of withdrawals interface.
type Mockwithdrawals struct {
	ctrl     *gomock.Controller
	recorder *MockwithdrawalsMockRecorder
	isgomock struct{}
}

// MockwithdrawalsMockRecorder is the mock recorder for Mockwithdrawals.
type MockwithdrawalsMockRecorder struct {
	mock *Mockwithdrawals
}

// NewMockwithdrawals creates a new mock instance.
func NewMockwithdrawals(ctrl *gomock.Controller) *Mockwithdrawals {
	mock := &Mockwithdrawals{ctrl: ctrl}
	mock.recorder = &MockwithdrawalsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockwithdrawals) EXPECT() *MockwithdrawalsMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *Mockwithdrawals) List(ctx context.Context, userID int64) ([]service.WithdrawResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].([]service.WithdrawResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockwithdrawalsMockRecorder) List(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*Mockwithdrawals)(nil).List), ctx, userID)
}
