// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go
//
// Generated by this command:
//
//	mockgen -source=auth.go -destination=mocks/mock_auth.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	query "github.com/korobkovandrey/gmartloyalty/db/query"
	gomock "go.uber.org/mock/gomock"
)

// Mockfinder is a mock of finder interface.
type Mockfinder struct {
	ctrl     *gomock.Controller
	recorder *MockfinderMockRecorder
	isgomock struct{}
}

// MockfinderMockRecorder is the mock recorder for Mockfinder.
type MockfinderMockRecorder struct {
	mock *Mockfinder
}

// NewMockfinder creates a new mock instance.
func NewMockfinder(ctrl *gomock.Controller) *Mockfinder {
	mock := &Mockfinder{ctrl: ctrl}
	mock.recorder = &MockfinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockfinder) EXPECT() *MockfinderMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *Mockfinder) Find(arg0 context.Context, arg1 int64) (*query.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(*query.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockfinderMockRecorder) Find(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*Mockfinder)(nil).Find), arg0, arg1)
}
